cache: apt
sudo: required
dist: trusty
matrix:
  include:
    - language: node_js
      node_js:
        - '12.13'
      before_install:
        - npm install npm@6.12 -g
      install:
        - npm ci --ignore-engines
      script:
        - npm run lint
        - npm test
